---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metric-gw-data
  namespace: metric-gw
  labels:
    app: metric-gw
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
